### ISSUE TITLE
Error while building under MacOS 12.6.3

### ISSUE THREAD

**Issue by joamag** [7thSamurai/Azayaka#2]
I'm getting this error while trying to compile Azayaka under MacOs 12.6.3:

```bash
[  1%] Building CXX object src/common/CMakeFiles/common.dir/bmp.cpp.o
In file included from /Users/joamag/Desktop/Azayaka/src/common/bmp.cpp:16:
In file included from /Users/joamag/Desktop/Azayaka/src/common/image.hpp:18:
/Users/joamag/Desktop/Azayaka/src/common/color.hpp:26:37: error: no type named 'size_t' in namespace 'std'
    std::uint8_t &operator [] (std::size_t i);
                               ~~~~~^
/Users/joamag/Desktop/Azayaka/src/common/color.hpp:27:37: error: no type named 'size_t' in namespace 'std'
    std::uint8_t  operator [] (std::size_t i) const;
                               ~~~~~^
2 errors generated.
```

It seems to be a MacOS-related issue but I decided to post it here to see if there's any obvious fix to this issue.

**Comment by joamag** [comment]
@7thSamurai any idea of what may be causing this?

**Comment by 7thSamurai** [comment]
Hello, thank you for reaching out.

Unfortunately as of right now the only supported system is Linux. I would like to add Mac support sometime in the future, but I currently don't have a Mac system to develop on, or the time to do so.

Sorry, but I'm going to have to close this issue for now for the reasons described above.
